# Generated by Django 4.1 on 2022-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteshop", "0002_contactitem_directoritem_galeryitem_textitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galeryitem",
            name="image",
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image1",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №1"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image2",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №2"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image3",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №3"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image4",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №4"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image5",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №5"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image6",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №6"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image7",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №7"
            ),
        ),
        migrations.AddField(
            model_name="galeryitem",
            name="image8",
            field=models.ImageField(
                default=0, upload_to="images", verbose_name="Фото в галерею №8"
            ),
        ),
    ]
