# Generated by Django 4.1 on 2022-09-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteshop", "0003_remove_galeryitem_image_galeryitem_image1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactItem",
        ),
        migrations.DeleteModel(
            name="DirectorItem",
        ),
    ]
